extensions:
  commerce/backend-ui/1:
    operations:
      view:
        - type: web
          impl: index.html
    actions: actions
    web: web-src
    runtimeManifest:
      packages:
        CustomGridColumns:
          license: Apache-2.0
          actions:
            get-customer-grid-columns:
              function: actions/data/customerGridColumns.js
              web: 'yes'
              runtime: 'nodejs:16'
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: false
                final: true
